version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
